import Head from 'next/head'
import styles from '../styles/Home.module.css'

// interface Test {
//  countries: string[]
// }

const Home = () => {
 return (
  <div className={styles.container}>
   <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
   </Head>

   <main className={styles.main}>test{typeof window === 'undefined' ? 'sdf' : 'sdfsdffd'}</main>
  </div>
 )
}

// export async function getServerSideProps() {
//  const { data } = await client.query({
//   query: gql`
//    query Countries {
//     countries {
//      code
//      name
//      emoji
//     }
//    }
//   `,
//  })

//  return {
//   props: {
//    countries: data.countries.slice(0, 4),
//   },
//  }
// }

export default Home
